### ISSUE TITLE
Remote repo URL does not work for init.el

### ISSUE THREAD

**Issue by lccambiaghi** [tecosaur/org-knit-action#2]
Hi, it's me again! Thanks for fixing the docker image. I now get a new error:
```
Traceback (most recent call last):
    File "/opt/org-knit/main.py", line 29, in <module>
      setup.config(I.config)
    File "/opt/org-knit/setup.py", line 34, in config
      raise FileNotFoundError(f"init.el is required.")
  FileNotFoundError: init.el is required.
```

[Here](https://github.com/lccambiaghi/nixpkgs/blob/main/.github/workflows/export.yml) is my setup

**Comment by tecosaur** [comment]
:thinking: I see you **do** have an `init.el`, not sure at a glance what's happening there.

I'll try to take a look later this week, if I seem to forget, please ping me.

**Comment by lccambiaghi** [comment]
Hi @tecosaur, sorry for the ping! Was just curious to know if you had some time to look into this action :)

**Comment by tecosaur** [comment]
Thanks for the ping. I'm afraid my week has ended up being busier than expected — would you mind waiting another ~week (if I don't get back to you *again* just ping me again 😛).

**Comment by lccambiaghi** [comment]
Hi @tecosaur here I am pinging you again! Sorry :D

**Comment by tecosaur** [comment]
Why is my life so busy? :sweat_smile: apologies again, haven't forgotten yet.

**Comment by tecosaur** [comment]
Ah, I've finally been able to try this out and work out what's happening.

So, because you give `https://github.com/lccambiaghi/vanilla-emacs` and not `https://github.com/lccambiaghi/vanilla-emacs.git` instead of being cloned that file is `wget`'d, and that's why it doesn't work.

The documentation definitely needs updating (sorry), but try adding `.git` :slightly_smiling_face:
